### ISSUE TITLE
Service 'Completeness' was not found

### ISSUE THREAD

**Issue by Vladzimir** [treolabs/completeness#1]
`> ComposerCmd::preUpdate
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing treolabs/completeness-common (1.0.2): Loading from cache
> ComposerCmd::postPackageInstall
  - Installing treolabs/completeness (1.12.1): Loading from cache
> ComposerCmd::postPackageInstall
Package container-interop/container-interop is abandoned, you should avoid using it. Use psr/container instead.
Package mtdowling/cron-expression is abandoned, you should avoid using it. Use dragonmantank/cron-expression instead.
Package zendframework/zend-loader is abandoned, you should avoid using it. Use laminas/laminas-loader instead.
Package zendframework/zend-mail is abandoned, you should avoid using it. Use laminas/laminas-mail instead.
Package zendframework/zend-mime is abandoned, you should avoid using it. Use laminas/laminas-mime instead.
Package zendframework/zend-servicemanager is abandoned, you should avoid using it. Use laminas/laminas-servicemanager instead.
Package zendframework/zend-stdlib is abandoned, you should avoid using it. Use laminas/laminas-stdlib instead.
Package zendframework/zend-validator is abandoned, you should avoid using it. Use laminas/laminas-validator instead.
Writing lock file
Generating autoload files
> ComposerCmd::postUpdate
18.05.2020 14:03:30 | Logout all...
18.05.2020 14:03:30 | Done!
18.05.2020 14:03:33 | Call after install event for Completeness... 
Script ComposerCmd::postUpdate handling the post-update-cmd event terminated with an exception

                                        
  [Espo\Core\Exceptions\Error]          
  Service 'Completeness' was not found  `

**Comment by m-kokhanskyi** [comment]
Before installation Completeness, create a custom/metadata/app/services.json file with a list of services:
{
  "Completeness": "\\Completeness\\Services\\Completeness",
  "CommonCompleteness": "\\Completeness\\Services\\CommonCompleteness",
  "CompletenessOverviewDashlet": "\\Completeness\\Services\\CompletenessOverviewDashlet",
  "QueueManagerMassUpdateComplete": "\\Completeness\\Services\\QueueManagerMassUpdateComplete"
}

**Comment by Vladzimir** [comment]
Similar problem when installing DAM. 
"Service 'Entity' was not found"

**Comment by rratsun** [comment]
Fix at 1.12.3
